CREATE OR REPLACE FORCE VIEW "SYSTEM".reporte1 (inquilino,telefono,vivienda_alquilada,propietario) AS
SELECT
    CONCAT(INQUILINO.APEINQ ,CONCAT(' ',INQUILINO.NOMINQ)) AS INQUILINO,
    TELINQ AS TELEFONO,
    CONCAT(VIVIENDA.CALVIV ,CONCAT(' ',CONCAT(VIVIENDA.NUMVIV ,CONCAT(' ',CONCAT('-' ,CONCAT(' ',VIVIENDA.DISVIV)))))) AS VIVIENDA_ALQUILADA,
    CONCAT(PROPIETARIO.APEPRO ,CONCAT(' ',PROPIETARIO.NOMPRO)) AS PROPIETARIO
FROM 
    ALQUILER
INNER JOIN VIVIENDA
ON ALQUILER.CODVIV = VIVIENDA.CODVIV
INNER JOIN PROPIETARIO
ON VIVIENDA.CODPRO = PROPIETARIO.CODPRO
INNER JOIN INQUILINO
ON ALQUILER.CODINQ = INQUILINO.CODINQ;