CREATE OR REPLACE FORCE VIEW "SYSTEM".reporte2 (agencia,vivienda,propietario) AS
SELECT
    CONCAT(ALQUILER.CODAGE ,CONCAT(' ',CONCAT('-' ,CONCAT(' ',AGENCIA.DIRAGE)))) AS AGENCIA,
    CONCAT(VIVIENDA.CALVIV ,CONCAT(' ',CONCAT(VIVIENDA.NUMVIV ,CONCAT(' ',CONCAT('-' ,CONCAT(' ',VIVIENDA.DISVIV)))))) AS VIVIENDA,
    CONCAT(PROPIETARIO.APEPRO ,CONCAT(' ',PROPIETARIO.NOMPRO)) AS PROPIETARIO
FROM 
    ALQUILER
INNER JOIN AGENCIA
ON ALQUILER.CODAGE = AGENCIA.CODAGE
INNER JOIN VIVIENDA
ON ALQUILER.CODVIV = VIVIENDA.CODVIV
INNER JOIN PROPIETARIO
ON VIVIENDA.CODPRO = PROPIETARIO.CODPRO;